### ISSUE TITLE
Sort direction arrows

### ISSUE THREAD

**Issue by ThiloL** [NonFactors/MVC5.Grid.Web#11]
I got confused about the sort direction arrows beside the column names.
I expect, that the arrows shows the current sort direction. But it seems to be the other way around.
What's the truth?

**Comment by Muchiachio** [comment]
They are showing current sort direction, but the problem is that different people interpret them in a different way, if they seem to be in reverse order, you can switch their order in css
```CSS
.mvc-grid .asc:after {
    content: '\2191';
}

.mvc-grid .desc:after {
    content: '\2193';
}
```
